In [5]:
# Importações básicas
from pyspark.sql import SparkSession
from pyspark.sql import Row
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from pyspark.sql.types import *
from pyspark.sql.functions import *
from datetime import date, timedelta
import random

In [6]:
# Lista de clientes
nome_cliente = [
    "Ana", "João", "Maria", "Pedro", "Júlia", "Lucas", "Larissa", "Gabriel", "Beatriz", "Felipe", "Clara",
    "Daniel", "Laura", "Rafael", "Mariana", "Gustavo", "Luísa", "Henrique", "Sofia", "Matheus", "Isabella",
    "Bruno", "Alice", "Thiago", "Helena", "Rodrigo", "Giovanna", "Eduardo", "Rafaela", "Leonardo", "Nicole",
    "Caio", "Vitória", "André", "Fernanda", "Diego", "Yasmin", "Guilherme", "Letícia", "Vinícius", "Camila",
    "Igor", "Valentina", "Otávio", "Bianca", "Enzo", "Lorena", "Alex", "Elisa", "Murilo", "Vitória", "Samuel",
    "Gabriela", "Arthur", "Evelyn", "Miguel", "Marina", "Renan", "Tainá", "Jorge", "Juliana", "Samuel",
    "Melissa", "Raul", "Camila", "Levi", "Carolina", "Nathan", "Cecília", "Lucas", "Amanda", "Benjamin",
    "Lívia", "Heitor", "Bruna", "Davi", "Talita", "Theo", "Maíra", "Tomás", "Ana Clara", "Vicente", "Isadora",
    "Alexandre", "Sabrina", "Emerson", "Thaís", "Renata", "Otávio", "Priscila", "Eduardo", "Natália", "Jonas",
    "Aline", "Cristiano", "Patrícia", "Vicente", "Elisa"
]

# Lista de estados
estados = ["SP", "RJ", "MG", "ES", "PR", "SC", "RS", "BA", "PE", "CE", "GO", "DF", "MT", "MS", "MA", "PA", "AM", "RO", "RR", "AC"]

# Lista de produtos eletrônicos
produtos = ["Smartphone", "Notebook", "Tablet", "Monitor", "Fone de Ouvido", "Smartwatch", "Câmera", "Impressora", "Caixa de Som", "Roteador"]

In [7]:
def gerardados(nome_cliente, estados, produtos):

    vendas = []
        
# Gera dados para número do pedido e código do cliente
    for dados in range(1,101):

        nrpedido = dados
        codcliente = random.randint(1, 100)  
        cliente = random.choice(nome_cliente)      
        qtd =  random.randint(1, 100)
        produto = random.choice(produtos)
        custo = float(random.uniform(1, 100))
        valor_venda = float(custo * 1.5)
        data_atual = date.today()
        data = data_atual - timedelta(days=random.randint(1, 30))        
        uf = random.choice(estados)        
        vendas.append((nrpedido, codcliente, cliente, qtd, produto, custo, valor_venda, data, uf))

    return vendas

In [8]:
gerardados(nome_cliente, estados, produtos)

[(1,
  27,
  'Nathan',
  56,
  'Câmera',
  36.80274440726905,
  55.20411661090358,
  datetime.date(2024, 6, 27),
  'GO'),
 (2,
  57,
  'Camila',
  84,
  'Câmera',
  96.0124864746816,
  144.01872971202238,
  datetime.date(2024, 7, 6),
  'RO'),
 (3,
  27,
  'Arthur',
  43,
  'Monitor',
  73.9276330303385,
  110.89144954550775,
  datetime.date(2024, 6, 23),
  'AM'),
 (4,
  30,
  'Isabella',
  42,
  'Smartphone',
  98.29523503758617,
  147.44285255637925,
  datetime.date(2024, 6, 20),
  'GO'),
 (5,
  1,
  'Fernanda',
  77,
  'Monitor',
  4.402724548663379,
  6.604086822995068,
  datetime.date(2024, 6, 18),
  'MS'),
 (6,
  12,
  'Vicente',
  10,
  'Caixa de Som',
  30.95956839446467,
  46.43935259169701,
  datetime.date(2024, 6, 12),
  'MA'),
 (7,
  64,
  'Henrique',
  31,
  'Tablet',
  23.752893146088024,
  35.629339719132034,
  datetime.date(2024, 6, 26),
  'MG'),
 (8,
  31,
  'Lucas',
  59,
  'Notebook',
  7.318852034464476,
  10.978278051696714,
  datetime.date(2024, 6, 28),
  'PA'),
 (9,
  87,
  'Melissa',
  85,
  'Caixa de Som',
  84.11013874715873,
  126.1652081207381,
  datetime.date(2024, 6, 23),
  'MT'),
 (10,
  44,
  'Priscila',
  82,
  'Caixa de Som',
  9.310315457916083,
  13.965473186874124,
  datetime.date(2024, 7, 3),
  'PA'),
 (11,
  50,
  'Lucas',
  10,
  'Fone de Ouvido',
  77.10895101491971,
  115.66342652237957,
  datetime.date(2024, 6, 18),
  'PR'),
 (12,
  48,
  'Tomás',
  25,
  'Caixa de Som',
  58.70716395561523,
  88.06074593342285,
  datetime.date(2024, 6, 26),
  'ES'),
 (13,
  28,
  'Ana',
  7,
  'Notebook',
  49.76957562602033,
  74.65436343903049,
  datetime.date(2024, 6, 19),
  'SC'),
 (14,
  74,
  'Cecília',
  86,
  'Smartphone',
  76.83878743515444,
  115.25818115273167,
  datetime.date(2024, 7, 1),
  'PE'),
 (15,
  63,
  'Enzo',
  97,
  'Impressora',
  99.01454240361706,
  148.5218136054256,
  datetime.date(2024, 7, 3),
  'AC'),
 (16,
  66,
  'Patrícia',
  42,
  'Notebook',
  88.53431675585506,
  132.8014751337826,
  datetime.date(2024, 6, 30),
  'GO'),
 (17,
  8,
  'Murilo',
  51,
  'Impressora',
  37.1045229122469,
  55.65678436837035,
  datetime.date(2024, 6, 15),
  'PR'),
 (18,
  49,
  'Fernanda',
  75,
  'Câmera',
  91.94770062026116,
  137.92155093039173,
  datetime.date(2024, 6, 24),
  'CE'),
 (19,
  31,
  'Felipe',
  96,
  'Impressora',
  50.465311352241756,
  75.69796702836263,
  datetime.date(2024, 7, 4),
  'MG'),
 (20,
  19,
  'Melissa',
  66,
  'Impressora',
  50.301219597732114,
  75.45182939659817,
  datetime.date(2024, 7, 1),
  'AM'),
 (21,
  62,
  'Matheus',
  81,
  'Roteador',
  28.948638710039162,
  43.422958065058744,
  datetime.date(2024, 6, 16),
  'RJ'),
 (22,
  27,
  'Laura',
  55,
  'Impressora',
  21.98854948011085,
  32.98282422016628,
  datetime.date(2024, 7, 9),
  'AM'),
 (23,
  10,
  'Eduardo',
  12,
  'Caixa de Som',
  59.48239421565244,
  89.22359132347866,
  datetime.date(2024, 6, 13),
  'AM'),
 (24,
  75,
  'Theo',
  84,
  'Caixa de Som',
  92.67421848941784,
  139.01132773412675,
  datetime.date(2024, 7, 3),
  'DF'),
 (25,
  33,
  'Sabrina',
  37,
  'Tablet',
  21.257607297418907,
  31.88641094612836,
  datetime.date(2024, 6, 19),
  'SP'),
 (26,
  47,
  'Murilo',
  2,
  'Impressora',
  45.14269531625573,
  67.7140429743836,
  datetime.date(2024, 6, 19),
  'SC'),
 (27,
  11,
  'Guilherme',
  57,
  'Smartphone',
  84.58686182824043,
  126.88029274236064,
  datetime.date(2024, 6, 29),
  'MT'),
 (28,
  22,
  'Sofia',
  16,
  'Smartwatch',
  82.20920759520156,
  123.31381139280234,
  datetime.date(2024, 6, 13),
  'CE'),
 (29,
  22,
  'Benjamin',
  61,
  'Fone de Ouvido',
  57.61813685286096,
  86.42720527929143,
  datetime.date(2024, 6, 24),
  'SC'),
 (30,
  4,
  'Luísa',
  73,
  'Câmera',
  1.0417850393087993,
  1.562677558963199,
  datetime.date(2024, 7, 5),
  'SC'),
 (31,
  89,
  'Heitor',
  58,
  'Monitor',
  88.41471620681378,
  132.62207431022068,
  datetime.date(2024, 6, 20),
  'RS'),
 (32,
  85,
  'Evelyn',
  44,
  'Monitor',
  82.92482343614259,
  124.38723515421388,
  datetime.date(2024, 6, 15),
  'PR'),
 (33,
  25,
  'Gustavo',
  46,
  'Roteador',
  6.795605578251995,
  10.193408367377993,
  datetime.date(2024, 6, 13),
  'CE'),
 (34,
  41,
  'Davi',
  53,
  'Fone de Ouvido',
  99.00564443415979,
  148.5084666512397,
  datetime.date(2024, 7, 5),
  'RS'),
 (35,
  13,
  'Fernanda',
  74,
  'Tablet',
  41.37540775863045,
  62.06311163794568,
  datetime.date(2024, 6, 23),
  'ES'),
 (36,
  55,
  'Evelyn',
  82,
  'Câmera',
  5.533786447528204,
  8.300679671292306,
  datetime.date(2024, 6, 22),
  'AM'),
 (37,
  67,
  'Talita',
  35,
  'Smartphone',
  50.506716966373965,
  75.76007544956094,
  datetime.date(2024, 6, 29),
  'GO'),
 (38,
  90,
  'Gabriel',
  62,
  'Tablet',
  7.0738153021997805,
  10.610722953299671,
  datetime.date(2024, 7, 5),
  'DF'),
 (39,
  2,
  'Samuel',
  27,
  'Tablet',
  32.90201748350977,
  49.35302622526466,
  datetime.date(2024, 6, 19),
  'MA'),
 (40,
  31,
  'Ana Clara',
  49,
  'Caixa de Som',
  92.86834486587605,
  139.30251729881408,
  datetime.date(2024, 6, 14),
  'MS'),
 (41,
  33,
  'Benjamin',
  15,
  'Smartphone',
  25.30562180705109,
  37.95843271057663,
  datetime.date(2024, 7, 1),
  'MA'),
 (42,
  31,
  'Sofia',
  5,
  'Smartwatch',
  35.26499359395733,
  52.89749039093599,
  datetime.date(2024, 6, 24),
  'BA'),
 (43,
  51,
  'Ana Clara',
  50,
  'Impressora',
  53.750673372630054,
  80.62601005894508,
  datetime.date(2024, 6, 20),
  'SC'),
 (44,
  43,
  'Eduardo',
  43,
  'Impressora',
  67.39170962812013,
  101.0875644421802,
  datetime.date(2024, 6, 25),
  'MS'),
 (45,
  16,
  'Maíra',
  3,
  'Câmera',
  19.11095908914816,
  28.66643863372224,
  datetime.date(2024, 6, 19),
  'RR'),
 (46,
  69,
  'Rodrigo',
  20,
  'Smartphone',
  74.29401423621276,
  111.44102135431913,
  datetime.date(2024, 6, 27),
  'RS'),
 (47,
  92,
  'Elisa',
  30,
  'Notebook',
  4.005457512391047,
  6.00818626858657,
  datetime.date(2024, 7, 3),
  'PE'),
 (48,
  36,
  'Bianca',
  74,
  'Notebook',
  15.782013628194656,
  23.673020442291985,
  datetime.date(2024, 7, 9),
  'DF'),
 (49,
  29,
  'Vitória',
  65,
  'Notebook',
  32.178810270435015,
  48.268215405652526,
  datetime.date(2024, 7, 2),
  'RJ'),
 (50,
  25,
  'Letícia',
  52,
  'Notebook',
  90.57101899399005,
  135.85652849098508,
  datetime.date(2024, 7, 8),
  'MA'),
 (51,
  88,
  'Lorena',
  89,
  'Câmera',
  27.813619906906162,
  41.720429860359246,
  datetime.date(2024, 7, 11),
  'PE'),
 (52,
  65,
  'Maria',
  90,
  'Impressora',
  64.06779173786752,
  96.10168760680128,
  datetime.date(2024, 7, 4),
  'GO'),
 (53,
  38,
  'Alexandre',
  24,
  'Fone de Ouvido',
  27.311293351079485,
  40.96694002661923,
  datetime.date(2024, 6, 19),
  'SC'),
 (54,
  73,
  'Lívia',
  42,
  'Monitor',
  20.045460414618727,
  30.06819062192809,
  datetime.date(2024, 7, 1),
  'ES'),
 (55,
  41,
  'Enzo',
  39,
  'Fone de Ouvido',
  68.31230353520351,
  102.46845530280527,
  datetime.date(2024, 6, 23),
  'CE'),
 (56,
  87,
  'Helena',
  10,
  'Smartphone',
  33.71768708345812,
  50.576530625187175,
  datetime.date(2024, 6, 23),
  'DF'),
 (57,
  62,
  'Melissa',
  16,
  'Câmera',
  94.41317641297361,
  141.61976461946043,
  datetime.date(2024, 7, 3),
  'SC'),
 (58,
  3,
  'Helena',
  7,
  'Notebook',
  30.033001130731922,
  45.049501696097884,
  datetime.date(2024, 6, 19),
  'MG'),
 (59,
  77,
  'Natália',
  59,
  'Notebook',
  29.640905310717525,
  44.461357966076285,
  datetime.date(2024, 6, 16),
  'MS'),
 (60,
  79,
  'Vicente',
  54,
  'Impressora',
  82.206362689173,
  123.30954403375951,
  datetime.date(2024, 7, 1),
  'SP'),
 (61,
  35,
  'Igor',
  34,
  'Smartwatch',
  2.362062489587897,
  3.543093734381846,
  datetime.date(2024, 6, 19),
  'PE'),
 (62,
  6,
  'Bruna',
  36,
  'Smartwatch',
  8.117362538219673,
  12.17604380732951,
  datetime.date(2024, 7, 7),
  'RR'),
 (63,
  75,
  'Thaís',
  73,
  'Caixa de Som',
  97.62947730573636,
  146.44421595860453,
  datetime.date(2024, 7, 1),
  'PE'),
 (64,
  90,
  'Igor',
  75,
  'Notebook',
  37.18507967224039,
  55.77761950836059,
  datetime.date(2024, 7, 3),
  'SP'),
 (65,
  53,
  'Isabella',
  68,
  'Smartwatch',
  64.38333168297214,
  96.57499752445821,
  datetime.date(2024, 6, 28),
  'DF'),
 (66,
  17,
  'Gustavo',
  32,
  'Caixa de Som',
  57.795873063178256,
  86.69380959476739,
  datetime.date(2024, 6, 14),
  'RJ'),
 (67,
  7,
  'Thiago',
  2,
  'Tablet',
  60.16417797731277,
  90.24626696596916,
  datetime.date(2024, 6, 12),
  'GO'),
 (68,
  17,
  'Thiago',
  55,
  'Monitor',
  40.61195926356251,
  60.91793889534377,
  datetime.date(2024, 7, 2),
  'PA'),
 (69,
  34,
  'Eduardo',
  98,
  'Smartwatch',
  35.47686981290056,
  53.21530471935084,
  datetime.date(2024, 6, 24),
  'MT'),
 (70,
  40,
  'Vicente',
  89,
  'Impressora',
  26.430320881350738,
  39.64548132202611,
  datetime.date(2024, 7, 11),
  'RJ'),
 (71,
  43,
  'Nicole',
  63,
  'Smartwatch',
  86.77695377626519,
  130.16543066439777,
  datetime.date(2024, 6, 27),
  'BA'),
 (72,
  4,
  'Heitor',
  17,
  'Impressora',
  3.3099983390654235,
  4.9649975085981355,
  datetime.date(2024, 6, 16),
  'MT'),
 (73,
  17,
  'Gabriel',
  2,
  'Smartphone',
  42.105835824293735,
  63.1587537364406,
  datetime.date(2024, 6, 13),
  'RR'),
 (74,
  17,
  'Pedro',
  20,
  'Impressora',
  10.47870417821037,
  15.718056267315553,
  datetime.date(2024, 7, 6),
  'PE'),
 (75,
  70,
  'Henrique',
  15,
  'Tablet',
  91.70763958934123,
  137.56145938401184,
  datetime.date(2024, 7, 5),
  'ES'),
 (76,
  83,
  'Júlia',
  64,
  'Fone de Ouvido',
  63.27790505985679,
  94.9168575897852,
  datetime.date(2024, 6, 25),
  'SC'),
 (77,
  44,
  'Talita',
  17,
  'Smartwatch',
  15.578403277180644,
  23.36760491577097,
  datetime.date(2024, 6, 23),
  'PR'),
 (78,
  9,
  'Lorena',
  42,
  'Fone de Ouvido',
  39.2405537543736,
  58.860830631560404,
  datetime.date(2024, 6, 19),
  'RS'),
 (79,
  74,
  'Letícia',
  50,
  'Fone de Ouvido',
  77.1333799759356,
  115.70006996390339,
  datetime.date(2024, 6, 12),
  'MA'),
 (80,
  73,
  'Eduardo',
  6,
  'Impressora',
  34.71078083420768,
  52.06617125131152,
  datetime.date(2024, 7, 4),
  'DF'),
 (81,
  88,
  'Rafael',
  12,
  'Roteador',
  58.510502697280195,
  87.76575404592029,
  datetime.date(2024, 6, 30),
  'MT'),
 (82,
  96,
  'Elisa',
  1,
  'Smartwatch',
  62.40259361568158,
  93.60389042352237,
  datetime.date(2024, 6, 22),
  'MS'),
 (83,
  51,
  'Rafael',
  78,
  'Monitor',
  70.77826342546051,
  106.16739513819076,
  datetime.date(2024, 6, 15),
  'GO'),
 (84,
  80,
  'Gabriela',
  29,
  'Roteador',
  17.613369722926866,
  26.4200545843903,
  datetime.date(2024, 6, 25),
  'GO'),
 (85,
  80,
  'Theo',
  69,
  'Impressora',
  83.50666480300589,
  125.25999720450884,
  datetime.date(2024, 6, 13),
  'MA'),
 (86,
  36,
  'Caio',
  83,
  'Fone de Ouvido',
  47.96985314317534,
  71.95477971476302,
  datetime.date(2024, 6, 27),
  'MA'),
 (87,
  74,
  'Eduardo',
  68,
  'Câmera',
  35.1239092274,
  52.6858638411,
  datetime.date(2024, 6, 26),
  'MS'),
 (88,
  45,
  'Rafaela',
  19,
  'Fone de Ouvido',
  85.24441238105116,
  127.86661857157674,
  datetime.date(2024, 7, 5),
  'ES'),
 (89,
  60,
  'Murilo',
  37,
  'Notebook',
  25.163353779522424,
  37.745030669283636,
  datetime.date(2024, 6, 14),
  'DF'),
 (90,
  14,
  'Bianca',
  58,
  'Roteador',
  88.0892343119592,
  132.1338514679388,
  datetime.date(2024, 7, 3),
  'PR'),
 (91,
  54,
  'Letícia',
  4,
  'Caixa de Som',
  92.05039466724556,
  138.07559200086834,
  datetime.date(2024, 7, 8),
  'RR'),
 (92,
  58,
  'Renata',
  10,
  'Notebook',
  57.82315808137768,
  86.73473712206652,
  datetime.date(2024, 7, 4),
  'ES'),
 (93,
  74,
  'Yasmin',
  29,
  'Câmera',
  76.54067861547747,
  114.81101792321621,
  datetime.date(2024, 6, 30),
  'RS'),
 (94,
  19,
  'Henrique',
  15,
  'Smartphone',
  62.96418723321695,
  94.44628084982543,
  datetime.date(2024, 6, 12),
  'CE'),
 (95,
  13,
  'Alex',
  48,
  'Fone de Ouvido',
  94.1582733057306,
  141.2374099585959,
  datetime.date(2024, 6, 29),
  'RJ'),
 (96,
  30,
  'Renata',
  79,
  'Câmera',
  98.11116125483207,
  147.16674188224812,
  datetime.date(2024, 7, 2),
  'BA'),
 (97,
  72,
  'Evelyn',
  21,
  'Smartwatch',
  62.58830631784392,
  93.88245947676589,
  datetime.date(2024, 6, 28),
  'RR'),
 (98,
  85,
  'Priscila',
  40,
  'Fone de Ouvido',
  10.485847227723166,
  15.72877084158475,
  datetime.date(2024, 6, 25),
  'MS'),
 (99,
  75,
  'Sofia',
  7,
  'Smartwatch',
  47.20776542770149,
  70.81164814155224,
  datetime.date(2024, 6, 26),
  'MT'),
 (100,
  47,
  'Felipe',
  59,
  'Smartphone',
  68.97183729858023,
  103.45775594787034,
  datetime.date(2024, 6, 19),
  'RO')]

In [122]:
spark = SparkSession.builder.appName(name="ecommerce").getOrCreate()

In [123]:
# Definindo o schema

schema = StructType([
    StructField("nrPedido", IntegerType(), True),
    StructField("codCliente", IntegerType(), True),
    StructField("cliente", StringType(), True),
    StructField("qtd", IntegerType(), True),
    StructField("produto", StringType(), True),
    StructField("custo", FloatType(), True),
    StructField("valorVenda", FloatType(), True),
    StructField("data", DateType(), True),    
    StructField("uf", StringType(), True)    
])

In [124]:
# Gerando dados fictícios de clientes para o DF
dados_vendas = gerardados(nome_cliente, estados, produtos)

In [125]:
# Atribuindo os dados ao df
df = spark.createDataFrame(dados_vendas, schema)

In [126]:
# Prévia dos dados.
df.limit(10).show()

+--------+----------+--------+---+------------+---------+----------+----------+---+
|nrPedido|codCliente| cliente|qtd|     produto|    custo|valorVenda|      data| uf|
+--------+----------+--------+---+------------+---------+----------+----------+---+
|       1|        31|    Enzo|  7|Caixa de Som|48.990036| 73.485054|2024-06-18| PE|
|       2|        50|  Nicole| 66|      Tablet| 42.06814| 63.102207|2024-06-29| DF|
|       3|         5|  Marina| 44|  Smartwatch|88.244415| 132.36662|2024-07-02| PA|
|       4|        61|   Sofia| 93|  Smartphone| 90.03038| 135.04558|2024-06-23| MG|
|       5|        88|    Alex| 45|  Smartwatch| 73.19159| 109.78738|2024-07-08| BA|
|       6|        34|Leonardo| 57|  Smartwatch| 62.14751|  93.22127|2024-07-09| RO|
|       7|        74|  Samuel|  3|  Impressora|23.550655|  35.32598|2024-07-09| DF|
|       8|        58| Letícia| 92|  Impressora|78.617805|117.926704|2024-06-22| RR|
|       9|        15|    Enzo| 25|      Tablet|49.270763|  73.90614|2024-06-27| PR|
|      10|        97|Gabriela| 72|  Impressora| 8.849226| 13.273839|2024-07-06| PR|
+--------+----------+--------+---+------------+---------+----------+----------+---+

In [14]:
# Identificando o schema
df.printSchema()

root
 |-- nrPedido: integer (nullable = true)
 |-- codCliente: integer (nullable = true)
 |-- cliente: string (nullable = true)
 |-- qtd: integer (nullable = true)
 |-- produto: string (nullable = true)
 |-- custo: float (nullable = true)
 |-- valorVenda: float (nullable = true)
 |-- data: date (nullable = true)
 |-- uf: string (nullable = true)

In [15]:
# Identificando o número total de linhas
df.count()

100

In [16]:
# Estados que tiveram apenas uma venda, e qual produto foi vendido
df.filter(df.qtd == 1).select(df.uf, df.produto).show()

+---+-------+
| uf|produto|
+---+-------+
+---+-------+

In [17]:
df.select(F.round(F.avg(col("valorVenda")), 2).alias("MediaVendas")).show()

+-----------+
|MediaVendas|
+-----------+
|      79.36|
+-----------+

In [18]:
## Forma alternativa para obter a média (complexa)

# Média de vendas
df_media_vendas = df.agg({"valorVenda": "avg"})

# Imprimindo e renomeando a coluna com o cálculo médio para melhor compreensão.
df_media_vendas = df_media_vendas.withColumnRenamed("avg(valorVenda)", "MediaVendas")

df_media_vendas.select(F.round(df_media_vendas.MediaVendas,2).alias("MediaVendas")).show()

+-----------+
|MediaVendas|
+-----------+
|      79.36|
+-----------+

In [19]:
# Produto mais vendido
#df.select(F.max("qtd")).show()
#df.orderBy(F.desc("qtd")).select("produto", "qtd").limit(1).show()
df_qtd_max = df.groupBy("produto").max("qtd").alias("total")
df_qtd_max.orderBy(F.desc("max(qtd)")).limit(3).show()

+------------+--------+
|     produto|max(qtd)|
+------------+--------+
|      Câmera|      98|
|  Smartphone|      94|
|Caixa de Som|      94|
+------------+--------+

In [20]:
df.groupBy("produto").sum("valorVenda").show()

+--------------+------------------+
|       produto|   sum(valorVenda)|
+--------------+------------------+
|  Caixa de Som| 1330.072036743164|
|    Smartwatch|  504.730845451355|
|      Roteador| 920.9131526947021|
|        Câmera| 592.5994186401367|
|      Notebook| 789.1409759521484|
|        Tablet| 551.6766014099121|
|    Smartphone| 801.1549077033997|
|       Monitor|1129.4624814987183|
|Fone de Ouvido| 963.2993354797363|
|    Impressora| 352.6999168395996|
+--------------+------------------+

In [21]:
df2 = (
    df.groupBy("Produto")
    .sum("valorVenda")
    .show(n=10)     
)

+--------------+------------------+
|       Produto|   sum(valorVenda)|
+--------------+------------------+
|  Caixa de Som| 1330.072036743164|
|    Smartwatch|  504.730845451355|
|      Roteador| 920.9131526947021|
|        Câmera| 592.5994186401367|
|      Notebook| 789.1409759521484|
|        Tablet| 551.6766014099121|
|    Smartphone| 801.1549077033997|
|       Monitor|1129.4624814987183|
|Fone de Ouvido| 963.2993354797363|
|    Impressora| 352.6999168395996|
+--------------+------------------+

In [22]:
dfduplicados = (
    df.groupBy(df.produto)
    .count()
    .filter(col("count") > 1)
    .sort("count", ascending=False)
    .limit(10)
    .show()
)

+--------------+-----+
|       produto|count|
+--------------+-----+
|  Caixa de Som|   17|
|      Roteador|   12|
|       Monitor|   12|
|    Smartphone|   11|
|Fone de Ouvido|   10|
|      Notebook|    9|
|        Tablet|    9|
|    Smartwatch|    7|
|        Câmera|    7|
|    Impressora|    6|
+--------------+-----+

In [23]:
# útil para análise exploratória de dados e para entender a relação entre duas variáveis categóricas no conjunto de dados.

df3 = df.crosstab("produto", "valorVenda").sort("produto_valorVenda").show()

24/07/12 19:24:50 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

+------------------+----------+---------+---------+----------+---------+---------+--------+---------+---------+----------+---------+----------+---------+---------+----------+---------+---------+---------+--------+---------+---------+---------+---------+---------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+--------+--------+---------+---------+---------+---------+---------+--------+---------+--------+---------+--------+---------+---------+---------+-------+---------+---------+--------+--------+--------+--------+---------+---------+--------+---------+--------+---------+--------+--------+---------+--------+---------+---------+---------+---------+--------+---------+---------+--------+--------+--------+--------+--------+---------+--------+--------+--------+---------+--------+--------+--------+--------+--------+--------+--------+---------+--------+--------+--------+--------+---------+--------+--------+
|produto_valorVenda|101.517685|102.70993|102.97576|108.230736|109.69108|11.865453|113.3425|115.84179|115.99811|119.708046|12.091312|120.244705|120.61674|121.63198|121.682556|127.02539|127.72047|13.525649|132.9143|135.27235|137.88586|138.51233|139.12735|139.24449|140.7949|140.89706|141.59012|142.00221|142.67738|144.01996|144.76508|145.33118|146.66028|147.55316|148.04709|148.57574|148.7064|15.39037|16.501932|17.464666|17.671064|19.221706|25.174204|25.30929|27.346573|27.72499|29.589151|29.88444|31.696085|31.731844|33.784554|34.4454|35.697037|38.356907|38.78946|39.07708|43.07636|43.56992|43.896816|44.144276|44.77524|45.689167|48.23285|48.805706|50.29994|50.71492|52.995995|53.58033|54.829998|55.641315|6.9536047|63.505714|63.77566|64.365715|65.593666|68.37007|7.145866|70.60881|76.10822|78.02568|78.085785|78.17231|78.81751|79.54786|80.804504|83.26158|83.75255|84.58069|85.84103|88.14883|88.67267|9.176982|93.189735|94.17578|94.24339|94.30042|95.28185|97.934204|97.97269|99.22955|
+------------------+----------+---------+---------+----------+---------+---------+--------+---------+---------+----------+---------+----------+---------+---------+----------+---------+---------+---------+--------+---------+---------+---------+---------+---------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+--------+--------+---------+---------+---------+---------+---------+--------+---------+--------+---------+--------+---------+---------+---------+-------+---------+---------+--------+--------+--------+--------+---------+---------+--------+---------+--------+---------+--------+--------+---------+--------+---------+---------+---------+---------+--------+---------+---------+--------+--------+--------+--------+--------+---------+--------+--------+--------+---------+--------+--------+--------+--------+--------+--------+--------+---------+--------+--------+--------+--------+---------+--------+--------+
|      Caixa de Som|         0|        0|        1|         1|        1|        1|       0|        1|        1|         0|        0|         0|        0|        0|         0|        0|        0|        0|       0|        0|        0|        0|        0|        0|       1|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        1|       0|       1|        0|        1|        0|        0|        0|       0|        0|       0|        0|       0|        0|        0|        0|      0|        1|        0|       0|       0|       0|       0|        0|        1|       0|        0|       0|        0|       0|       0|        0|       0|        1|        0|        0|        0|       0|        1|        0|       0|       0|       0|       0|       0|        0|       0|       1|       1|        0|       0|       0|       0|       1|       0|       0|       0|        0|       0|       0|       0|       0|        0|       0|       0|
|            Câmera|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        0|         1|        0|        0|        0|       0|        0|        0|        0|        0|        0|       0|        0|        0|        0|        0|        0|        0|        0|        1|        0|        0|        0|       0|       0|        0|        0|        0|        0|        0|       0|        0|       1|        0|       0|        0|        0|        0|      0|        0|        0|       1|       0|       0|       0|        0|        0|       0|        0|       0|        0|       0|       0|        0|       0|        0|        0|        0|        0|       0|        0|        1|       0|       0|       0|       0|       0|        0|       0|       0|       0|        0|       0|       0|       0|       0|       0|       0|       0|        0|       1|       0|       0|       0|        0|       1|       0|
|    Fone de Ouvido|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         1|        0|        0|         0|        0|        0|        0|       1|        0|        0|        0|        0|        0|       0|        0|        0|        1|        0|        0|        0|        0|        0|        1|        0|        0|       0|       0|        0|        0|        0|        0|        0|       0|        0|       0|        0|       0|        0|        0|        0|      0|        0|        0|       0|       0|       0|       0|        0|        0|       1|        0|       0|        0|       1|       0|        0|       0|        0|        1|        0|        0|       0|        0|        0|       0|       0|       0|       0|       0|        0|       0|       0|       0|        0|       1|       0|       0|       0|       0|       1|       0|        0|       0|       0|       0|       0|        1|       0|       0|
|        Impressora|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        0|         0|        0|        0|        0|       0|        0|        0|        0|        0|        0|       0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|       0|       0|        1|        0|        0|        0|        0|       0|        0|       0|        0|       0|        0|        1|        0|      0|        0|        0|       0|       0|       0|       0|        0|        0|       0|        0|       0|        0|       0|       0|        0|       0|        0|        0|        0|        1|       0|        0|        0|       0|       0|       1|       1|       0|        0|       0|       0|       0|        0|       0|       0|       0|       0|       0|       0|       0|        0|       0|       1|       0|       0|        0|       0|       0|
|           Monitor|         1|        1|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        0|         0|        1|        1|        1|       0|        1|        0|        1|        0|        0|       0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|       0|       0|        0|        0|        0|        0|        0|       0|        0|       0|        0|       0|        0|        0|        0|      0|        0|        0|       0|       0|       0|       1|        0|        0|       0|        0|       0|        0|       0|       0|        0|       0|        0|        0|        0|        0|       0|        0|        0|       0|       0|       0|       0|       0|        1|       0|       0|       0|        0|       0|       1|       1|       0|       0|       0|       0|        1|       0|       0|       0|       0|        0|       0|       0|
|          Notebook|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        0|         0|        0|        0|        0|       0|        0|        0|        0|        1|        0|       0|        1|        0|        0|        0|        0|        0|        0|        0|        0|        1|        0|       0|       0|        0|        0|        0|        1|        0|       0|        0|       0|        0|       0|        0|        0|        0|      0|        0|        0|       0|       0|       0|       0|        0|        0|       0|        1|       0|        0|       0|       0|        1|       1|        0|        0|        0|        0|       0|        0|        0|       0|       0|       0|       0|       0|        0|       0|       0|       0|        0|       0|       0|       0|       0|       0|       0|       0|        0|       0|       0|       1|       1|        0|       0|       0|
|          Roteador|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        1|         0|        0|        0|        0|       0|        0|        0|        0|        0|        0|       0|        0|        0|        0|        1|        0|        0|        0|        0|        0|        0|        0|       1|       0|        0|        0|        0|        0|        1|       0|        1|       0|        0|       0|        0|        0|        0|      0|        0|        0|       0|       1|       1|       0|        1|        0|       0|        0|       0|        0|       0|       0|        0|       0|        0|        0|        0|        0|       1|        0|        0|       0|       0|       0|       0|       0|        0|       1|       0|       0|        0|       0|       0|       0|       0|       1|       0|       0|        0|       0|       0|       0|       0|        0|       0|       1|
|        Smartphone|         0|        0|        0|         0|        0|        0|       1|        0|        0|         0|        0|         0|        0|        0|         0|        0|        0|        0|       0|        0|        1|        0|        0|        0|       0|        0|        1|        0|        0|        1|        0|        0|        0|        0|        0|        0|       0|       0|        0|        0|        0|        0|        0|       0|        0|       0|        0|       1|        0|        0|        0|      0|        0|        1|       0|       0|       0|       0|        0|        0|       0|        0|       1|        0|       0|       1|        0|       0|        0|        0|        0|        0|       0|        0|        0|       0|       1|       0|       0|       0|        0|       0|       0|       0|        1|       0|       0|       0|       0|       0|       0|       1|        0|       0|       0|       0|       0|        0|       0|       0|
|        Smartwatch|         0|        0|        0|         0|        0|        0|       0|        0|        0|         0|        0|         0|        0|        0|         0|        0|        0|        0|       0|        0|        0|        0|        0|        0|       0|        0|        0|        0|        0|        0|        1|        1|        0|        0|        0|        0|       0|       0|        0|        0|        0|        0|        0|       0|        0|       0|        1|       0|        1|        0|        0|      0|        0|        0|       0|       0|       0|       0|        0|        0|       0|        0|       0|        0|       0|       0|        0|       0|        0|        0|        1|        0|       0|        0|        0|       1|       0|       0|       0|       1|        0|       0|       0|       0|        0|       0|       0|       0|       0|       0|       0|       0|        0|       0|       0|       0|       0|        0|       0|       0|
|            Tablet|         0|        0|        0|         0|        0|        0|       0|        0|        0|         1|        1|         0|        1|        0|         0|        0|        0|        0|       0|        0|        0|        0|        0|        1|       0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|        0|       0|       0|        0|        0|        1|        0|        0|       1|        0|       0|        0|       0|        0|        0|        1|      1|        0|        0|       0|       0|       0|       0|        0|        0|       0|        0|       0|        1|       0|       0|        0|       0|        0|        0|        0|        0|       0|        0|        0|       0|       0|       0|       0|       0|        0|       0|       0|       0|        0|       0|       0|       0|       0|       0|       0|       0|        0|       0|       0|       0|       0|        0|       0|       0|
+------------------+----------+---------+---------+----------+---------+---------+--------+---------+---------+----------+---------+----------+---------+---------+----------+---------+---------+---------+--------+---------+---------+---------+---------+---------+--------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+---------+--------+--------+---------+---------+---------+---------+---------+--------+---------+--------+---------+--------+---------+---------+---------+-------+---------+---------+--------+--------+--------+--------+---------+---------+--------+---------+--------+---------+--------+--------+---------+--------+---------+---------+---------+---------+--------+---------+---------+--------+--------+--------+--------+--------+---------+--------+--------+--------+---------+--------+--------+--------+--------+--------+--------+--------+---------+--------+--------+--------+--------+---------+--------+--------+

In [24]:
# Dropando dados duplicados

df.dropDuplicates().show(10)

+--------+----------+--------+---+--------------+---------+----------+----------+---+
|nrPedido|codCliente| cliente|qtd|       produto|    custo|valorVenda|      data| uf|
+--------+----------+--------+---+--------------+---------+----------+----------+---+
|       6|        80|  Otávio| 60|      Notebook| 98.69806| 148.04709|2024-07-08| PR|
|      17|         8|  Heitor| 48|    Smartphone| 25.57127| 38.356907|2024-06-28| BA|
|       1|         2|Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA|
|      18|         9| Vicente| 24|      Roteador|52.114872|  78.17231|2024-06-23| BA|
|      24|        32|  Arthur| 98|        Câmera|25.859638|  38.78946|2024-06-18| GO|
|       4|        21| Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA|
|      21|        27|  Miguel|  6|  Caixa de Som| 77.22786| 115.84179|2024-06-13| PR|
|      11|        73|   Jorge| 66|       Monitor| 9.017099| 13.525649|2024-07-11| ES|
|      13|        11|   Elisa| 71|Fone de Ouvido| 80.16314|120.244705|2024-07-11| MS|
|      10|        89|Isabella|  2|      Roteador|28.717571|  43.07636|2024-07-11| RJ|
+--------+----------+--------+---+--------------+---------+----------+----------+---+
only showing top 10 rows

# Trabalhando com datas

In [25]:
# Ajustando a formatação da data para PT-BR
df.select(df.cliente, df.qtd, df.valorVenda, F.date_format('Data', "dd/MM/yyyy").alias("data")).show()

+---------+---+----------+----------+
|  cliente|qtd|valorVenda|      data|
+---------+---+----------+----------+
| Vinícius| 22| 140.89706|16/06/2024|
|    André| 70| 138.51233|27/06/2024|
|   Nicole| 60| 31.696085|17/06/2024|
|  Gustavo| 36| 141.59012|22/06/2024|
|    Clara| 65|  43.56992|19/06/2024|
|   Otávio| 60| 148.04709|08/07/2024|
|Alexandre| 90|  84.58069|04/07/2024|
|    Sofia| 35|  94.17578|26/06/2024|
| Patrícia| 49| 17.671064|20/06/2024|
| Isabella|  2|  43.07636|11/07/2024|
|    Jorge| 66| 13.525649|11/07/2024|
|  Rodrigo|  2|  85.84103|17/06/2024|
|    Elisa| 71|120.244705|11/07/2024|
|  Isadora| 16| 52.995995|28/06/2024|
|   Camila| 62|  83.26158|16/06/2024|
|  Gabriel| 83| 139.24449|12/06/2024|
|   Heitor| 48| 38.356907|28/06/2024|
|  Vicente| 24|  78.17231|23/06/2024|
|   Daniel|  6| 115.99811|19/06/2024|
|  Matheus| 52| 44.144276|08/07/2024|
+---------+---+----------+----------+
only showing top 20 rows

In [26]:
# Consultando vendas em um período específico, sem utilizar o alias
df4 = df.select(
    df.produto,
    df.data.between("2024-06-01", "2024-06-10")).limit(10).show()

+----------+-----------------------------------------------+
|   produto|((data >= 2024-06-01) AND (data <= 2024-06-10))|
+----------+-----------------------------------------------+
|  Notebook|                                          false|
|   Monitor|                                          false|
|Smartwatch|                                          false|
|Smartphone|                                          false|
|   Monitor|                                          false|
|  Notebook|                                          false|
|   Monitor|                                          false|
|    Câmera|                                          false|
|    Tablet|                                          false|
|  Roteador|                                          false|
+----------+-----------------------------------------------+

In [27]:
# Consultando vendas em um período específico, utilizando o alias, para melhorar a visualização
df.select(
    df.produto,
    df.data,
    df.data.between("2024-06-01", "2024-06-10").alias("dentroPeriodo")).limit(10).show()

+----------+----------+-------------+
|   produto|      data|dentroPeriodo|
+----------+----------+-------------+
|  Notebook|2024-06-16|        false|
|   Monitor|2024-06-27|        false|
|Smartwatch|2024-06-17|        false|
|Smartphone|2024-06-22|        false|
|   Monitor|2024-06-19|        false|
|  Notebook|2024-07-08|        false|
|   Monitor|2024-07-04|        false|
|    Câmera|2024-06-26|        false|
|    Tablet|2024-06-20|        false|
|  Roteador|2024-07-11|        false|
+----------+----------+-------------+

In [28]:
# 5. *Custo Médio por Estado:  - Qual é o custo médio dos produtos vendidos em cada estado?
df.select(round(F.avg(col("custo")),2).alias("custoMedio")).show()

+----------+
|custoMedio|
+----------+
|      52.9|
+----------+

In [29]:
# 6. *Total de Vendas por Cliente: Qual é o total de vendas (valor de venda) por cliente?

df_total_por_clientes = (
    df
    .groupBy("cliente")
    .agg(F.round(F.sum("valorVenda"),2).alias("totalPorCliente"))
    .withColumnRenamed("sum(valorVenda)", "totalPorCliente")
    .show(10)
)

+--------+---------------+
| cliente|totalPorCliente|
+--------+---------------+
|   André|         138.51|
|  Amanda|         132.91|
|Isabella|         119.58|
| Rodrigo|          85.84|
|  Nicole|           31.7|
| Gabriel|         139.24|
|  Arthur|         134.07|
|   Clara|          43.57|
|Vinícius|          140.9|
|   Jorge|          30.03|
+--------+---------------+
only showing top 10 rows

In [30]:
# 7. Data Mais Recente e Mais Antiga: Qual é a data mais recente e a mais antiga registrada nos dados?
df_antigo_recente = (
    df
    .select(min(df.data)
    .alias("antigo"),
    max(df.data)
    .alias("recente"))
    .show()
)

+----------+----------+
|    antigo|   recente|
+----------+----------+
|2024-06-12|2024-07-11|
+----------+----------+

In [31]:
# 8. *Quantidade de Vendas por Dia: Quantas vendas ocorreram em cada dia?
df_total_diario = (
    df
    .groupBy(date_format("data", "dd/MM/yyyy").alias("data"))
    .agg(round(sum("valorVenda"),2)
    .alias("TotalVendaDiaria"))
    .limit(10)
    .show()
)

+----------+----------------+
|      data|TotalVendaDiaria|
+----------+----------------+
|26/06/2024|          106.04|
|19/06/2024|          440.04|
|16/06/2024|           649.9|
|11/07/2024|          299.96|
|08/07/2024|          640.48|
|18/06/2024|           141.5|
|27/06/2024|          212.03|
|12/06/2024|          549.87|
|23/06/2024|          527.63|
|22/06/2024|          307.93|
+----------+----------------+

In [32]:
# 9. *Custo Médio e Valor de Venda Médio por Produto: Qual é o custo médio e o valor de venda médio para cada produto?
df_custoMedio_vendaMedia = (
    df.groupBy("produto")    
    .agg(round(avg("custo"),2)    
    .alias("custoMedio"),
    round(avg("valorVenda"))
    .alias("receitaMedia"))
    .limit(10)
    .show()
)

+--------------+----------+------------+
|       produto|custoMedio|receitaMedia|
+--------------+----------+------------+
|  Caixa de Som|     52.16|        78.0|
|    Smartwatch|     48.07|        72.0|
|      Roteador|     51.16|        77.0|
|        Câmera|     56.44|        85.0|
|      Notebook|     58.45|        88.0|
|        Tablet|     40.86|        61.0|
|    Smartphone|     48.55|        73.0|
|       Monitor|     62.75|        94.0|
|Fone de Ouvido|     64.22|        96.0|
|    Impressora|     39.19|        59.0|
+--------------+----------+------------+

In [33]:
# 10. *Porcentagem de Lucro: Qual é a porcentagem média de lucro (baseado no custo e valor de venda) em todas as vendas?
custo_venda = df.withColumn("custoTotal", (df.qtd * df.custo))
custo_venda.show()

+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
|nrPedido|codCliente|  cliente|qtd|       produto|    custo|valorVenda|      data| uf|custoTotal|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
|       1|         2| Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA| 2066.4902|
|       2|        79|    André| 70|       Monitor| 92.34155| 138.51233|2024-06-27| PR| 6463.9087|
|       3|        49|   Nicole| 60|    Smartwatch|21.130724| 31.696085|2024-06-17| MS| 1267.8434|
|       4|        21|  Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA| 3398.1628|
|       5|        81|    Clara| 65|       Monitor|29.046614|  43.56992|2024-06-19| RJ| 1888.0299|
|       6|        80|   Otávio| 60|      Notebook| 98.69806| 148.04709|2024-07-08| PR|  5921.884|
|       7|       100|Alexandre| 90|       Monitor|56.387127|  84.58069|2024-07-04| MG| 5074.8413|
|       8|        69|    Sofia| 35|        Câmera|62.783855|  94.17578|2024-06-26| MS|  2197.435|
|       9|        48| Patrícia| 49|        Tablet|11.780709| 17.671064|2024-06-20| AM| 577.25476|
|      10|        89| Isabella|  2|      Roteador|28.717571|  43.07636|2024-07-11| RJ| 57.435143|
|      11|        73|    Jorge| 66|       Monitor| 9.017099| 13.525649|2024-07-11| ES| 595.12854|
|      12|        50|  Rodrigo|  2|  Caixa de Som| 57.22735|  85.84103|2024-06-17| ES|  114.4547|
|      13|        11|    Elisa| 71|Fone de Ouvido| 80.16314|120.244705|2024-07-11| MS|  5691.583|
|      14|        53|  Isadora| 16|      Notebook| 35.33066| 52.995995|2024-06-28| RJ|  565.2906|
|      15|        67|   Camila| 62|Fone de Ouvido| 55.50772|  83.26158|2024-06-16| DF| 3441.4788|
|      16|        69|  Gabriel| 83|        Tablet| 92.82966| 139.24449|2024-06-12| RR|  7704.862|
|      17|         8|   Heitor| 48|    Smartphone| 25.57127| 38.356907|2024-06-28| BA| 1227.4209|
|      18|         9|  Vicente| 24|      Roteador|52.114872|  78.17231|2024-06-23| BA|  1250.757|
|      19|        18|   Daniel|  6|  Caixa de Som| 77.33207| 115.99811|2024-06-19| RO| 463.99243|
|      20|        17|  Matheus| 52|  Caixa de Som|29.429518| 44.144276|2024-07-08| PR|  1530.335|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
only showing top 20 rows

In [34]:
lucro_percentual = custo_venda.withColumn("lucroPercentual", (custo_venda.custoTotal * custo_venda.valorVenda) / 100)
lucro_percentual.show()

+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+-----------------+
|nrPedido|codCliente|  cliente|qtd|       produto|    custo|valorVenda|      data| uf|custoTotal|  lucroPercentual|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+-----------------+
|       1|         2| Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA| 2066.4902|     2911.6240625|
|       2|        79|    André| 70|       Monitor| 92.34155| 138.51233|2024-06-27| PR| 6463.9087|      8953.310625|
|       3|        49|   Nicole| 60|    Smartwatch|21.130724| 31.696085|2024-06-17| MS| 1267.8434|     401.85671875|
|       4|        21|  Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA| 3398.1628|     4811.4628125|
|       5|        81|    Clara| 65|       Monitor|29.046614|  43.56992|2024-06-19| RJ| 1888.0299|       822.613125|
|       6|        80|   Otávio| 60|      Notebook| 98.69806| 148.04709|2024-07-08| PR|  5921.884|       8767.17625|
|       7|       100|Alexandre| 90|       Monitor|56.387127|  84.58069|2024-07-04| MG| 5074.8413|      4292.335625|
|       8|        69|    Sofia| 35|        Câmera|62.783855|  94.17578|2024-06-26| MS|  2197.435|     2069.4515625|
|       9|        48| Patrícia| 49|        Tablet|11.780709| 17.671064|2024-06-20| AM| 577.25476| 102.007060546875|
|      10|        89| Isabella|  2|      Roteador|28.717571|  43.07636|2024-07-11| RJ| 57.435143|24.74096923828125|
|      11|        73|    Jorge| 66|       Monitor| 9.017099| 13.525649|2024-07-11| ES| 595.12854|           80.495|
|      12|        50|  Rodrigo|  2|  Caixa de Som| 57.22735|  85.84103|2024-06-17| ES|  114.4547|   98.24908203125|
|      13|        11|    Elisa| 71|Fone de Ouvido| 80.16314|120.244705|2024-07-11| MS|  5691.583|        6843.8275|
|      14|        53|  Isadora| 16|      Notebook| 35.33066| 52.995995|2024-06-28| RJ|  565.2906|   299.5813671875|
|      15|        67|   Camila| 62|Fone de Ouvido| 55.50772|  83.26158|2024-06-16| DF| 3441.4788|     2865.4296875|
|      16|        69|  Gabriel| 83|        Tablet| 92.82966| 139.24449|2024-06-12| RR|  7704.862|      10728.59625|
|      17|         8|   Heitor| 48|    Smartphone| 25.57127| 38.356907|2024-06-28| BA| 1227.4209|    470.800703125|
|      18|         9|  Vicente| 24|      Roteador|52.114872|  78.17231|2024-06-23| BA|  1250.757|       977.745625|
|      19|        18|   Daniel|  6|  Caixa de Som| 77.33207| 115.99811|2024-06-19| RO| 463.99243|   538.2224609375|
|      20|        17|  Matheus| 52|  Caixa de Som|29.429518| 44.144276|2024-07-08| PR|  1530.335|      675.5553125|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+-----------------+
only showing top 20 rows

# Trabalhando com datas

In [35]:
#11) Data Mais Recente e Mais Antiga: Objetivo: Descobrir qual é a data mais recente e a mais antiga registrada nos dados.

data_recente_antiga = (
    df.select(
        F.max(date_format("data", "dd/MM/yyyy"))
        .alias("dataAntiga"), 
        F.min(date_format("data", "dd/MM/yyyy"))
        .alias("dataRecente"))
)

data_recente_antiga.show()

+----------+-----------+
|dataAntiga|dataRecente|
+----------+-----------+
|29/06/2024| 01/07/2024|
+----------+-----------+

In [36]:
# 12) Quantidade de Vendas por Dia. Objetivo: Contar quantas vendas ocorreram em cada dia.
#df.groupBy("data").agg(sum("qtd").alias("qtdDia")).show()
df_qtdDia = (
    df.groupBy("data")
    .agg(sum("qtd").alias("qtdDia"))    
    .sort("data")
)

df_qtdDia.show()

+----------+------+
|      data|qtdDia|
+----------+------+
|2024-06-12|   264|
|2024-06-13|    54|
|2024-06-14|   169|
|2024-06-15|    36|
|2024-06-16|   309|
|2024-06-17|   179|
|2024-06-18|   173|
|2024-06-19|   161|
|2024-06-20|   350|
|2024-06-21|   222|
|2024-06-22|   138|
|2024-06-23|   210|
|2024-06-24|   122|
|2024-06-25|   187|
|2024-06-26|   123|
|2024-06-27|   154|
|2024-06-28|   192|
|2024-06-29|    59|
|2024-07-01|    47|
|2024-07-02|    10|
+----------+------+
only showing top 20 rows

# Adicionar Coluna com Ano e Mês. Objetivo: Adicionar uma coluna que contenha apenas o ano e o mês da data da venda.

In [37]:
# 13) Adicionar Coluna com Ano e Mês Objetivo: Adicionar uma coluna que contenha apenas o ano e o mês da data da venda.
df_ano_mes = df.withColumn("ano_mes", date_format(df.data, "yyyy-MM"))
df_ano_mes.show()

+--------+----------+---------+---+--------------+---------+----------+----------+---+-------+
|nrPedido|codCliente|  cliente|qtd|       produto|    custo|valorVenda|      data| uf|ano_mes|
+--------+----------+---------+---+--------------+---------+----------+----------+---+-------+
|       1|         2| Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA|2024-06|
|       2|        79|    André| 70|       Monitor| 92.34155| 138.51233|2024-06-27| PR|2024-06|
|       3|        49|   Nicole| 60|    Smartwatch|21.130724| 31.696085|2024-06-17| MS|2024-06|
|       4|        21|  Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA|2024-06|
|       5|        81|    Clara| 65|       Monitor|29.046614|  43.56992|2024-06-19| RJ|2024-06|
|       6|        80|   Otávio| 60|      Notebook| 98.69806| 148.04709|2024-07-08| PR|2024-07|
|       7|       100|Alexandre| 90|       Monitor|56.387127|  84.58069|2024-07-04| MG|2024-07|
|       8|        69|    Sofia| 35|        Câmera|62.783855|  94.17578|2024-06-26| MS|2024-06|
|       9|        48| Patrícia| 49|        Tablet|11.780709| 17.671064|2024-06-20| AM|2024-06|
|      10|        89| Isabella|  2|      Roteador|28.717571|  43.07636|2024-07-11| RJ|2024-07|
|      11|        73|    Jorge| 66|       Monitor| 9.017099| 13.525649|2024-07-11| ES|2024-07|
|      12|        50|  Rodrigo|  2|  Caixa de Som| 57.22735|  85.84103|2024-06-17| ES|2024-06|
|      13|        11|    Elisa| 71|Fone de Ouvido| 80.16314|120.244705|2024-07-11| MS|2024-07|
|      14|        53|  Isadora| 16|      Notebook| 35.33066| 52.995995|2024-06-28| RJ|2024-06|
|      15|        67|   Camila| 62|Fone de Ouvido| 55.50772|  83.26158|2024-06-16| DF|2024-06|
|      16|        69|  Gabriel| 83|        Tablet| 92.82966| 139.24449|2024-06-12| RR|2024-06|
|      17|         8|   Heitor| 48|    Smartphone| 25.57127| 38.356907|2024-06-28| BA|2024-06|
|      18|         9|  Vicente| 24|      Roteador|52.114872|  78.17231|2024-06-23| BA|2024-06|
|      19|        18|   Daniel|  6|  Caixa de Som| 77.33207| 115.99811|2024-06-19| RO|2024-06|
|      20|        17|  Matheus| 52|  Caixa de Som|29.429518| 44.144276|2024-07-08| PR|2024-07|
+--------+----------+---------+---+--------------+---------+----------+----------+---+-------+
only showing top 20 rows

In [38]:
# 14) Filtrar Vendas de um Mês Específico. Objetivo: Filtrar todas as vendas que ocorreram no mês de julho de 2024.
df.filter((year(col("data")) == 2024) & (month(col("data")) == 6)).show(10)

+--------+----------+--------+---+--------------+---------+----------+----------+---+
|nrPedido|codCliente| cliente|qtd|       produto|    custo|valorVenda|      data| uf|
+--------+----------+--------+---+--------------+---------+----------+----------+---+
|       1|         2|Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA|
|       2|        79|   André| 70|       Monitor| 92.34155| 138.51233|2024-06-27| PR|
|       3|        49|  Nicole| 60|    Smartwatch|21.130724| 31.696085|2024-06-17| MS|
|       4|        21| Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA|
|       5|        81|   Clara| 65|       Monitor|29.046614|  43.56992|2024-06-19| RJ|
|       8|        69|   Sofia| 35|        Câmera|62.783855|  94.17578|2024-06-26| MS|
|       9|        48|Patrícia| 49|        Tablet|11.780709| 17.671064|2024-06-20| AM|
|      12|        50| Rodrigo|  2|  Caixa de Som| 57.22735|  85.84103|2024-06-17| ES|
|      14|        53| Isadora| 16|      Notebook| 35.33066| 52.995995|2024-06-28| RJ|
|      15|        67|  Camila| 62|Fone de Ouvido| 55.50772|  83.26158|2024-06-16| DF|
+--------+----------+--------+---+--------------+---------+----------+----------+---+
only showing top 10 rows

# Adicionar Coluna com Dia da Semana. Objetivo: Adicionar uma coluna que mostre o dia da semana para cada data de venda.

In [39]:
# 15) Adicionar Coluna com Dia da Semana. Objetivo: Adicionar uma coluna que mostre o dia da semana para cada data de venda.
df_dia_semana = df.withColumn("dia_semana", date_format(df.data, "EEEE"))
df_dia_semana.show()

+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
|nrPedido|codCliente|  cliente|qtd|       produto|    custo|valorVenda|      data| uf|dia_semana|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
|       1|         2| Vinícius| 22|      Notebook| 93.93137| 140.89706|2024-06-16| BA|    Sunday|
|       2|        79|    André| 70|       Monitor| 92.34155| 138.51233|2024-06-27| PR|  Thursday|
|       3|        49|   Nicole| 60|    Smartwatch|21.130724| 31.696085|2024-06-17| MS|    Monday|
|       4|        21|  Gustavo| 36|    Smartphone| 94.39341| 141.59012|2024-06-22| MA|  Saturday|
|       5|        81|    Clara| 65|       Monitor|29.046614|  43.56992|2024-06-19| RJ| Wednesday|
|       6|        80|   Otávio| 60|      Notebook| 98.69806| 148.04709|2024-07-08| PR|    Monday|
|       7|       100|Alexandre| 90|       Monitor|56.387127|  84.58069|2024-07-04| MG|  Thursday|
|       8|        69|    Sofia| 35|        Câmera|62.783855|  94.17578|2024-06-26| MS| Wednesday|
|       9|        48| Patrícia| 49|        Tablet|11.780709| 17.671064|2024-06-20| AM|  Thursday|
|      10|        89| Isabella|  2|      Roteador|28.717571|  43.07636|2024-07-11| RJ|  Thursday|
|      11|        73|    Jorge| 66|       Monitor| 9.017099| 13.525649|2024-07-11| ES|  Thursday|
|      12|        50|  Rodrigo|  2|  Caixa de Som| 57.22735|  85.84103|2024-06-17| ES|    Monday|
|      13|        11|    Elisa| 71|Fone de Ouvido| 80.16314|120.244705|2024-07-11| MS|  Thursday|
|      14|        53|  Isadora| 16|      Notebook| 35.33066| 52.995995|2024-06-28| RJ|    Friday|
|      15|        67|   Camila| 62|Fone de Ouvido| 55.50772|  83.26158|2024-06-16| DF|    Sunday|
|      16|        69|  Gabriel| 83|        Tablet| 92.82966| 139.24449|2024-06-12| RR| Wednesday|
|      17|         8|   Heitor| 48|    Smartphone| 25.57127| 38.356907|2024-06-28| BA|    Friday|
|      18|         9|  Vicente| 24|      Roteador|52.114872|  78.17231|2024-06-23| BA|    Sunday|
|      19|        18|   Daniel|  6|  Caixa de Som| 77.33207| 115.99811|2024-06-19| RO| Wednesday|
|      20|        17|  Matheus| 52|  Caixa de Som|29.429518| 44.144276|2024-07-08| PR|    Monday|
+--------+----------+---------+---+--------------+---------+----------+----------+---+----------+
only showing top 20 rows

In [55]:
# 16) Determinar o Dia da Semana com Mais Vendas
# Objetivo: Descobrir qual dia da semana teve o maior número de vendas totais (soma das quantidades vendidas).

df_dia_semana_total_qtd = (
    df_dia_semana
    .groupBy("dia_semana")
    .agg(sum("qtd").alias("qtd"))
    .sort("qtd", ascending=False)    
)

df_dia_semana_total_qtd.show()

+----------+---+
|dia_semana|qtd|
+----------+---+
|  Thursday|931|
| Wednesday|829|
|    Monday|734|
|    Sunday|728|
|    Friday|673|
|   Tuesday|527|
|  Saturday|313|
+----------+---+

In [142]:
# 17) Calcular a Média de Vendas por Mês:
# Objetivo: Calcular a média da quantidade de vendas realizadas em cada mês.

df_media_vendas_mes = (
    df.groupBy(month("data")
               .alias("MesCorrespondente"))
    .agg(round(sum("valorVenda"),2)
         .alias("TotalPorMes"))
)

df_media_vendas_mes.show()

+-----------------+-----------+
|MesCorrespondente|TotalPorMes|
+-----------------+-----------+
|                6|    4474.97|
|                7|    3185.53|
+-----------------+-----------+